spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb+srv://${USERNAME_MONGODB_CHAT:username}:${PASSWORD_MONGODB_CHAT:ljAluvRtFZxPfAa7}@chat.5aber6f.mongodb.net/?retryWrites=true&w=majority&appName=chat
      database: chat

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual # publisher-returns: message unacknowledged
        concurrency: 2 # many consumers for one queue
        max-concurrency: 10 # max number of consumers for one queue
        prefetch: 5 # number of messages to prefetch
        shutdown-timeout: 10s
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2.0
        default-requeue-rejected: false
file:
  upload:
    max-size: ${FILE_MAX_SIZE:10}
    allowed-types: image/jpeg,image/png,image/gif,image/webp
    max-images: ${MAX_IMAGES:10}
    image:
      max-width: ${IMAGE_MAX_WIDTH:1920}
      max-height: ${IMAGE_MAX_HEIGHT:1080}
      thumbnail-size: ${THUMBNAIL_WIDTH:300}
      compress-quality: ${COMPRESS_QUALITY:0.8}

websocket:
  allow-origin: "*"
  endpoint: /ws
  destination-prefix: /topic,/queue
  application-prefix: /app
  user-destination-prefix: /user

rabbitmq:
  exchange:
    chat: ex.chat
    notification: ex.notification
  routing-keys:
    message: rk.message
    notification: rk.notification.send

supabase:
  url: ${SUPABASE_URL}
  service-key: ${SUPABASE_SERVICE_KEY}
  bucket: ${SUPABASE_BUCKET:upload-images}
  public-url: ${SUPABASE_PUBLIC_URL}

feign:
  client:
    config:
      profile-service:
        url: "http://localhost:8082"
      item-service:
        url: "http://localhost:8083"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: reuse-hub
    version: 1.0.0
