spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      uri: mongodb+srv://${USERNAME_MONGODB:username}:${PASSWORD_MONGODB:ljAluvRtFZxPfAa7}@chat.5aber6f.mongodb.net/?retryWrites=true&w=majority&appName=chat
      database: chat

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual # publisher-returns: message unacknowledged
        concurrency: 2 # many consumers for one queue
        max-concurrency: 10 # max number of consumers for one queue
        prefetch: 5 # number of messages to prefetch
        shutdown-timeout: 10s
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          max-interval: 10000ms
          multiplier: 2.0
        default-requeue-rejected: false

websocket:
  allow-origin: "*"
  endpoint: /ws
  destination-prefix: /topic,/queue
  application-prefix: /app
  user-destination-prefix: /user
chat:
  message:
    cache-ttl: 3600 # seconds
  presence:
    timeout: 300 # seconds
  typing:
    timeout: 10 # seconds

rabbitmq:
  exchange:
    chat: chat.exchange
  queues:
    message: chat.message.queue
    presence: chat.presence.queue
    typing: chat.typing.queue
  routing-keys:
    message: chat.message
    presence: chat.presence
    typing: chat.typing

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: chat-service
    version: 1.0.0
