spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DATABASE_URL_ITEM:jdbc:postgresql://localhost:5432/profile}
    username: ${SUPABASE_DB_USERNAME:postgres}
    password: ${SUPABASE_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        spatial:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect

supabase:
  url: ${SUPABASE_URL:https://gpkseonjcemtkylobsfq.supabase.co}
  service-key: ${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwa3Nlb25qY2VtdGt5bG9ic2ZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTYxODE3MSwiZXhwIjoyMDc1MTk0MTcxfQ.XBZiLqY1BYPi27ZCpZ6GRkC3G8ZGkT63B1iMy0klxe8}
  bucket: ${SUPABASE_BUCKET:upload-images}
  public-url: ${SUPABASE_PUBLIC_URL:https://gpkseonjcemtkylobsfq.storage.supabase.co/storage/v1/object/public}

file:
  upload:
    max-size: ${FILE_MAX_SIZE:10}
    allowed-types: image/jpeg,image/png,image/gif,image/webp
    max-images: ${MAX_IMAGES:10}
    image:
      max-width: ${IMAGE_MAX_WIDTH:1920}
      max-height: ${IMAGE_MAX_HEIGHT:1080}
      thumbnail-size: ${THUMBNAIL_WIDTH:300}
      compress-quality: ${COMPRESS_QUALITY:0.8}

avatar:
  default: https://i.ibb.co/mrL8wYRs/default.jpg

rabbitmq:
  queues:
    user-profile-creation: q.profile.create

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: reuse-hub-api-docs
    server: ${BACKEND_SERVICE:http://localhost:${server.port}}
    title: profile-service
    version: 1.0.0
